improve ignores

diff --git a/.github/workflows/links-verify.yml b/.github/workflows/links-verify.yml
--- a/.github/workflows/links-verify.yml
+++ b/.github/workflows/links-verify.yml
@@ -28,12 +28,11 @@ jobs:
       # we filter out the domains: pan.dev, paloaltonetworks.com
       run: |
         grep -RPoz "(?s)## Commands.*\Z|<h2>Commands.*\Z" --include "README.md" content/Packs/*/Integrations \
-        | grep  -Poa "(http|https)://[a-zA-Z0-9./?=_%:-]*" \
+        | grep -i -Poa "(http|https)://[a-zA-Z0-9./?=_%:-]*" \
         | grep -v -i pan.dev \
         | grep -v -i paloaltonetworks.com \
         | sort -u > all_urls_ignore.txt
-        sed -i -e 's/^/-e "/' all_urls_ignore.txt
-        sed -i -e 's/$/"/' all_urls_ignore.txt
+        sed -i -e 's/^/-e /' all_urls_ignore.txt
         cat content-docs/.github/workflows/urls_ignore.txt >> all_urls_ignore.txt
         cat all_urls_ignore.txt
     - name: Set up Go 1.19
@@ -45,14 +44,15 @@ jobs:
       run: 'go install github.com/raviqqe/muffet/v2@latest'
     - name: Verify Links
       # If there are false positives, add ignore urls to .github/workflows/urls_ignore.txt file
+      # we use set -f to avoid globing in the shell
       run: |
         muffet --version
         echo "Running test curl..."
         curl -v https://xsoar.pan.dev > /dev/null
         echo "Running muffet link checking"
-        muffet -v -c 16 --ignore-fragments -b 8192 --skip-tls-verification \
+        (set -f; muffet -v -c 16 --ignore-fragments -b 8192 --skip-tls-verification \
         `cat content-docs/.github/workflows/urls_ignore.txt` \
-        https://xsoar.pan.dev > muffet.txt 2>&1 && echo "muffet completed successfully" && exit 0 || echo "muffet failed but still need to verify output file..."
+        https://xsoar.pan.dev > muffet.txt 2>&1 && echo "muffet completed successfully" && exit 0 || echo "muffet failed but still need to verify output file...")
         grep -v -E '^\s+(401|403|405|429|x509|lookup|parse|timeout|dial)' muffet.txt > muffet-clean.out
         echo "Muffet output after 401, 403, 405, 429 and x509 remove:"
         cat muffet-clean.out
