muffet

diff --git a/.github/workflows/links-verify.yml b/.github/workflows/links-verify.yml
--- a/.github/workflows/links-verify.yml
+++ b/.github/workflows/links-verify.yml
@@ -34,29 +34,29 @@ jobs:
         cat content-docs/urls_ignore.txt >> out.txt
         sort -u out.txt
         cat out.txt
-#    - name: Set up Go 1.13
-#      uses: actions/setup-go@v2
-#      with:
-#        go-version: 1.13.11
-#      id: go
-#    - name: Setup muffet
-#      run: 'go get -u github.com/raviqqe/muffet'
-#    - name: Verify Links
-#      run: |
-#        muffet --version
-#        muffet $(< out.txt) -c 16 --ignore-fragments -b 8192 \
-#        https://xsoar.pan.dev > muffet.txt 2>&1 && echo "muffet completed successfully" && exit 0 || echo "muffet failed but still need to verify output file..."
-#        grep -v -E '^\s+(401|403|405|429|x509|lookup|parse|timeout|dial)' muffet.txt > muffet-clean.out
-#        echo "Muffet output after 401, 403, 405, 429 and x509 remove:"
-#        cat muffet-clean.out
-#        if [ -n "$(grep -v '^https'  muffet-clean.out)" ]; then
-#          echo "muffet failed verification!!!"
-#          exit 1
-#        fi
-#        echo "All good! muffet passed!!!"
-#    - name: Save artifcats
-#      if: ${{ always() }}
-#      uses: actions/upload-artifact@v2
-#      with:
-#        name: log-artifacts
-#        path: muffet.txt
+    - name: Set up Go 1.13
+      uses: actions/setup-go@v2
+      with:
+        go-version: 1.13.11
+      id: go
+    - name: Setup muffet
+      run: 'go get -u github.com/raviqqe/muffet'
+    - name: Verify Links
+      run: |
+        muffet --version
+        muffet $(< out.txt) -c 16 --ignore-fragments -b 8192 \
+        https://xsoar.pan.dev > muffet.txt 2>&1 && echo "muffet completed successfully" && exit 0 || echo "muffet failed but still need to verify output file..."
+        grep -v -E '^\s+(401|403|405|429|x509|lookup|parse|timeout|dial)' muffet.txt > muffet-clean.out
+        echo "Muffet output after 401, 403, 405, 429 and x509 remove:"
+        cat muffet-clean.out
+        if [ -n "$(grep -v '^https'  muffet-clean.out)" ]; then
+          echo "muffet failed verification!!!"
+          exit 1
+        fi
+        echo "All good! muffet passed!!!"
+    - name: Save artifcats
+      if: ${{ always() }}
+      uses: actions/upload-artifact@v2
+      with:
+        name: log-artifacts
+        path: muffet.txt
