save muffet log

diff --git a/.github/workflows/links-verify.yml b/.github/workflows/links-verify.yml
--- a/.github/workflows/links-verify.yml
+++ b/.github/workflows/links-verify.yml
@@ -1,7 +1,7 @@
 name: Verify Site Links
 
 on:
-  # push: {} #  uncommnet for testing
+  push: {} #  uncommnet for testing
   schedule: # daily at 12 noon UTC
     - cron: '0 12 * * *'
 
@@ -46,8 +46,8 @@ jobs:
         -e 'https://api.*.crowdstrike.com.*' \
         -e 'https://dehashed.com.*' \
         -e 'https://secure.aadcdn.microsoftonline-p.com.*' \
-        https://xsoar.pan.dev > muffet.out 2>&1 && echo "muffet completed successfully" && exit 0 || echo "muffet failed but still need to verify output file..."
-        grep -v -E '^\s+(403|401|x509|lookup|parse|timeout|dialing)' muffet.out > muffet-clean.out
+        https://xsoar.pan.dev > muffet.txt 2>&1 && echo "muffet completed successfully" && exit 0 || echo "muffet failed but still need to verify output file..."
+        grep -v -E '^\s+(403|401|x509|lookup|parse|timeout|dialing)' muffet.txt > muffet-clean.out
         echo "Muffet output after 401, 403 and x509 remove:"
         cat muffet-clean.out
         if [ -n "$(grep -v '^https'  muffet-clean.out)" ]; then
@@ -55,3 +55,8 @@ jobs:
           exit 1
         fi
         echo "All good muffet passed!!!"
+    - name: Save artifcats
+      uses: actions/upload-artifact@v2
+        with:
+          name: log-artifacts
+          path: muffet.txt
